FROM docker.io/library/node:alpine AS build-stage

WORKDIR /
COPY . .
RUN npm clean-install && npm run build

FROM docker.io/library/nginx:alpine-slim

RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx
RUN chmod g+rw /etc/nginx/conf.d/default.conf
RUN sed -i.bak 's/listen\(.*\)80;/listen 8081;/' /etc/nginx/conf.d/default.conf
RUN sed -i.bak 's/^user/#user/' /etc/nginx/nginx.conf

COPY --from=build-stage /dist/ /usr/share/nginx/html/

EXPOSE 8081
