FROM docker.io/library/node:alpine AS build-stage

WORKDIR /
COPY . .
RUN npm clean-install && npm run build

FROM docker.io/library/nginx:alpine-slim

RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx

COPY --from=build-stage /default.conf.template /etc/nginx/templates/
COPY --from=build-stage /dist/ /usr/share/nginx/html/

EXPOSE 8081
