FROM docker.io/library/golang:alpine AS build-stage

WORKDIR /build
COPY . .
RUN go build -o /build/start-server

FROM docker.io/library/alpine

WORKDIR /app
COPY --from=build-stage /build/start-server ./

EXPOSE 5001

CMD ["./start-server"]
