FROM registry.access.redhat.com/ubi9/nodejs-18-minimal

ENV TZ="Europe/Helsinki"

USER slowers

WORKDIR /home/slowers/app

ARG BASE_PATH
ENV BASE_PATH=$BASE_PATH

ARG STAGING
ENV STAGING=$STAGING

ARG E2E
ENV E2E=$E2E

COPY . .

WORKDIR /home/slowers/app/frontend
RUN \
    npm install && \
    npm run build && \
    mkdir ../backend/client && \
    mv dist ../backend/client/

WORKDIR /home/slowers/app/backend

EXPOSE 5001

CMD ["go", "run", "main.go"]
